[tasks.web]
script = [
 "cargo build --target wasm32-unknown-unknown --release",
 "wasm-gc target/wasm32-unknown-unknown/release/utils.wasm -o utils.gc.wasm",
 "http"
]

[tasks.format]
description = "Runs the cargo rustfmt plugin."
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]
